name: mcs_tracking
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1
version: 0.0.8
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.2.0
  percent_indicator:
  font_awesome_flutter: ^8.11.0
  animated_text_kit:
  shared_preferences:
  http:
  loading_overlay:
  email_validator:
  flappy_search_bar:
  flutter_spinkit:
  stomp_dart_client:
  flutter_launcher_icons: "^0.8.0"
  simple_animations: ^1.3.3
  progress_dialog: ^1.2.4
  dio: ^3.0.10
  get_it: ^5.0.0
  provider: ^4.3.2+2
  flutter_animarker: ^0.1.1+1
  charts_flutter: ^0.9.0
  shimmer: ^1.1.2
#  connectivity: ^2.0.2
  fl_chart: ^0.12.1
  date_format: ^1.0.9
  fluttertoast: ^7.1.6
  intl: ^0.16.1
  lottie: ^0.7.0+1
  jwt_decoder: ^1.0.4
  geolocator: ^6.2.0
  geocoder: ^0.2.1
  google_maps_place_picker:
  dropdown_search: ^0.4.8
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo_new.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Light.ttf
          weight: 200
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-Thin.ttf
          weight: 300
          # style: italic
    - family: Amita
      fonts:
        - asset: fonts/Amita-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
